//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankCoding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMoneyAccount
    {
        public int IdMoneyAccount { get; set; }
        public Nullable<int> IdAccount { get; set; }
        public Nullable<decimal> Money { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
    }
}
