//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankCoding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParameter
    {
        public int IdParameter { get; set; }
        public string Parameter { get; set; }
        public decimal Value { get; set; }
        public string Descripcion { get; set; }
    }
}
